apiVersion: v1
kind: Service
metadata:
  name: demo-be-service-dev
  namespace: demo-dev-ns
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: demo-be-dep-dev
