apiVersion: v1
kind: Service
metadata:
  name: demo-be-service-prod
  namespace: demo-prod-ns
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: demo-be-dep-prod
