apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-deployment
        track: stable
    spec:
      containers:
        - name: demo-deployment
          image: "gcr.io/ml-console-dev/demo-backend-image:latest"
          # resources:
          #   requests:
          #     memory: "1000Mi"
          #     cpu: "150m"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          ports:
            - name: demo-port
              containerPort: 3000