apiVersion: v1
kind: Service
metadata:
  name: demo-backend-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: demo-backend-service